name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract and join commit messages
        id: process_commits
        run: |
          COMMIT_MESSAGES=$(git log --pretty=format:%s --no-merges)
          echo "JOINED_COMMIT_MESSAGES=$(echo $COMMIT_MESSAGES | tr '\n' ' ')" >> $GITHUB_ENV
      - name: Bump version and push tag
        if: ${{github.event_name == 'push' && !contains(env.JOINED_COMMIT_MESSAGES, '#skip') }}
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'patch'

  discord_notification:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: always()
    steps:
      - name: Discord notification failure
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        if: ${{ failure() }}
        with:  
          args: 'Commit [${{ github.event.after }}](https://github.com/${{ github.repository }}/commit/${{ github.event.after }}) broke the build'
        
      - name: Discord notification success
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        if: ${{ success() }}
        with:
          args: 'The project ${{ github.repository }} has been deployed.'

